name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Asegúrate de que se ejecute en Node.js 20

      - name: Setup Node
        uses: actions/setup-node@v3  # Asegúrate de que se ejecute en Node.js 20
        with:
          node-version: '20'  # Especificamos la versión 20 de Node.js

      - name: Install dependencies
        uses: bahmutov/npm-install@v1  # Sin cambios

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Sin cambios
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Sin cambios
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Sin cambios
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
